### ISSUE TITLE
EXTREMELY IMPORTANT

### ISSUE THREAD

**Issue by aslonv** [joshuaiz/bio-dark-theme#1] opened 2020-12-31 04:22 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I installed a "Live Server' extension by Ritwick Dey. After the that a "Live Server" button should have appeared underneath the VS code, but it did not appear and the live server is no working

Extension version: 0.1.5
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.13GB free)|
|Process Argv|-n --crash-reporter-id 7a111715-ea6d-4801-9d18-25211b874c75|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2prompt:30224612
pythonvsdeb440cf:30237828
unusedpromptcf:30224611
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773cf:30236630
vsjup459cf:30237188

```

</details>

**Comment by joshuaiz** [comment] 2020-12-31 18:05
@BegaliAslon have you reached out to the Live Server devs? I doubt this has anything to do with this theme.

Can you provide any screenshots? I'm not quite sure what the issue is.

**Comment by aslonv** [comment] 2021-01-01 10:00
Hello Joshua!

Thank you for the response. I honestly don't know how to reach to the Live
Server devs, and actually it's my first time using VS code and learning to
code.

One problem I have noticed is underneath the VS code screen of my Youtube
teacher there is a Life Server button. But the same button does not appear
on my screen.

Sending you a screenshot.

чт, 31 дек. 2020 г., 19:05 Joshua Michaels <notifications@github.com>:

**Comment by joshuaiz** [comment] 2021-01-01 18:56
@BegaliAslon Here is the repo for Live Server: https://github.com/ritwickdey/vscode-live-server

I suggest reading through the existing issues there and if your issue hasn't already been solved, post an issue with their repo as this is unrelated to the Bio Dark Theme (this repo).

Closing.

**Closed as completed by joshuaiz** 2021-01-01 18:56 UTC
